
services:
  database:
    image: mysql:8.0
    container_name: prtf_sql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      MYSQL_USER: ${MYSQL_USER:-user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
    
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - symfony_network

  symfony:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: PORTFOLIO
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - database
    networks:
      - symfony_network
    environment:
      COMPOSER_ALLOW_SUPERUSER: "1" # Enable Composer plugins as superuser

volumes:
  mysql_data: {} # Volume for MySQL data persistence

networks:
  symfony_network:
    driver: bridge
