controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
    path: /
    controller: App\Controller\HomeController::index

resume:
    path: /resume
    controller: App\Controller\ResumeController::index

contact:
    path: /contact
    controller: App\Controller\UserController::create