controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# about_me:
#     path: /about-me
#     controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
#     defaults:
#         template: 'About_me/About_me.html.twig'